In [2]:
import pandas as pd

df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "HR", "Finance"],
    "Salary": [60000, 50000, 65000, 52000, 70000],
    "Gender": ["M", "F", "F", "M", "F"]
})

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Department  5 non-null      object
 1   Salary      5 non-null      int64
 2   Gender      5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [3]:
df.head()

  Department  Salary Gender
0         IT   60000      M
1         HR   50000      F
2         IT   65000      F
3         HR   52000      M
4    Finance   70000      F

In [6]:
df.groupby('Department')['Gender'].value_counts()

Department  Gender
Finance     F         1
HR          F         1
            M         1
IT          F         1
            M         1
Name: count, dtype: int64

In [7]:
df.groupby('Department')['Salary'].mean()

Department
Finance    70000.0
HR         51000.0
IT         62500.0
Name: Salary, dtype: float64

In [9]:
df.groupby(['Department','Gender']).size().reset_index(name = 'Count')

  Department Gender  Count
0    Finance      F      1
1         HR      F      1
2         HR      M      1
3         IT      F      1
4         IT      M      1

In [44]:
df.groupby('Department')['Salary'].mean().sort_values(ascending=False).head(n=3)

Department
Finance    70000.0
IT         62500.0
HR         51000.0
Name: Salary, dtype: float64

In [18]:
df.groupby('Gender').agg(Salary =("Salary",lambda x:x.max()-x.min()))

        Salary
Gender
F        20000
M         8000

In [3]:
df = pd.read_csv(r'C:/users/dsaiv/Downloads/titanic.csv')

In [47]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [13]:
df.sort_values(by='Age',ascending=False).groupby('Pclass').head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S

In [14]:
df.groupby('Embarked')['Fare'].mean()

Embarked
C    59.954144
Q    13.276030
S    27.079812
Name: Fare, dtype: float64

In [49]:
df.groupby('Pclass')['Age'].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [17]:
df.groupby('Sex')['Survived'].count()

Sex
female    314
male      577
Name: Survived, dtype: int64

In [50]:
df.groupby('Sex')["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [27]:
df['Prompt'] = df.apply( lambda row: f"{row['Name']}, bought ticket of {row['Pclass']} rd Class for {row['Fare']} Embarked on {row['Embarked']}",axis=1)

In [23]:
df['Prompt'] = df.apply(lambda row: f"{row['Name']}",axis=1)

In [28]:
df['Prompt']

0      Braund, Mr. Owen Harris, bought ticket of 3 rd...
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2      Heikkinen, Miss. Laina, bought ticket of 3 rd ...
3      Futrelle, Mrs. Jacques Heath (Lily May Peel), ...
4      Allen, Mr. William Henry, bought ticket of 3 r...
                             ...
886    Montvila, Rev. Juozas, bought ticket of 2 rd C...
887    Graham, Miss. Margaret Edith, bought ticket of...
888    Johnston, Miss. Catherine Helen "Carrie", boug...
889    Behr, Mr. Karl Howell, bought ticket of 1 rd C...
890    Dooley, Mr. Patrick, bought ticket of 3 rd Cla...
Name: Prompt, Length: 891, dtype: object

In [51]:
df.groupby('Embarked')["Fare"].sum()

Embarked
C    10072.2962
Q     1022.2543
S    17439.3988
Name: Fare, dtype: float64

In [52]:
df.groupby(['Pclass','Sex']).agg({
    'Age':'mean',
    'Survived':'mean'
})

                     Age  Survived
Pclass Sex
1      female  34.611765  0.968085
       male    41.281386  0.368852
2      female  28.722973  0.921053
       male    30.740707  0.157407
3      female  21.750000  0.500000
       male    26.507589  0.135447

In [53]:
df.groupby(['Pclass','Sex'])['Survived'].mean().unstack()

Sex       female      male
Pclass
1       0.968085  0.368852
2       0.921053  0.157407
3       0.500000  0.135447

In [ ]:
Swap every two adjacent number and return list. You must solve the problem without modifying the values in the list.
Example 1:
Input: list1 = [1,2,3,4]
Output: [2,1,4,3]
Example 2:
Input: list2 = [1,2,3]
Output: [2,1,3]

In [7]:
nums = [1,2,3,4]
no_swaps = len(nums)//2
for i in range(0,no_swaps):
    j = 0
    nums[j],nums[j+1] = nums[j+1],nums[j]
    j+=2
print(nums)

[1, 2, 3, 4]

In [1]:
nums1 = [0,0]
nums2 = [1,2]
nums1 = nums2
print(nums1)

[1, 2]

ahsuyh