In [42]:
import pandas as pd

df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "HR", "Finance"],
    "Salary": [60000, 50000, 65000, 52000, 70000],
    "Gender": ["M", "F", "F", "M", "F"]
})

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Department  5 non-null      object
 1   Salary      5 non-null      int64
 2   Gender      5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [3]:
df.head()

  Department  Salary Gender
0         IT   60000      M
1         HR   50000      F
2         IT   65000      F
3         HR   52000      M
4    Finance   70000      F

In [6]:
df.groupby('Department')['Gender'].value_counts()

Department  Gender
Finance     F         1
HR          F         1
            M         1
IT          F         1
            M         1
Name: count, dtype: int64

In [7]:
df.groupby('Department')['Salary'].mean()

Department
Finance    70000.0
HR         51000.0
IT         62500.0
Name: Salary, dtype: float64

In [9]:
df.groupby(['Department','Gender']).size().reset_index(name = 'Count')

  Department Gender  Count
0    Finance      F      1
1         HR      F      1
2         HR      M      1
3         IT      F      1
4         IT      M      1

In [44]:
df.groupby('Department')['Salary'].mean().sort_values(ascending=False).head(n=3)

Department
Finance    70000.0
IT         62500.0
HR         51000.0
Name: Salary, dtype: float64

In [18]:
df.groupby('Gender').agg(Salary =("Salary",lambda x:x.max()-x.min()))

        Salary
Gender
F        20000
M         8000

In [46]:
df = pd.read_csv(r'C:/users/dsaiv/Downloads/titanic.csv')

In [47]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [48]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [49]:
df.groupby('Pclass')['Age'].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [50]:
df.groupby('Sex')["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [51]:
df.groupby('Embarked')["Fare"].sum()

Embarked
C    10072.2962
Q     1022.2543
S    17439.3988
Name: Fare, dtype: float64

In [52]:
df.groupby(['Pclass','Sex']).agg({
    'Age':'mean',
    'Survived':'mean'
})

                     Age  Survived
Pclass Sex
1      female  34.611765  0.968085
       male    41.281386  0.368852
2      female  28.722973  0.921053
       male    30.740707  0.157407
3      female  21.750000  0.500000
       male    26.507589  0.135447

In [53]:
df.groupby(['Pclass','Sex'])['Survived'].mean().unstack()

Sex       female      male
Pclass
1       0.968085  0.368852
2       0.921053  0.157407
3       0.500000  0.135447